# docker build -f Dockerfile-plus-profile -t accetto/ubuntu-vnc-xfce-firefox-plus-profile .
# docker build -f Dockerfile-plus-profile --build-arg BASETAG=rolling -t accetto/ubuntu-vnc-xfce-firefox-plus-profile:rolling .

ARG BASETAG=latest

FROM accetto/ubuntu-vnc-xfce-firefox-plus:${BASETAG}

LABEL \
    any.accetto.description="Headless Ubuntu VNC/noVNC container with Xfce desktop and Firefox with profile" \
    any.accetto.display-name="Headless Ubuntu/Xfce VNC/noVNC container with Firefox profile"

### Arguments can be provided during build
ARG ARG_VNC_BLACKLIST_THRESHOLD
ARG ARG_VNC_BLACKLIST_TIMEOUT
ARG ARG_VNC_RESOLUTION
ARG ARG_VNC_USER

ENV \
  VNC_BLACKLIST_THRESHOLD=${ARG_VNC_BLACKLIST_THRESHOLD:-20} \
  VNC_BLACKLIST_TIMEOUT=${ARG_VNC_BLACKLIST_TIMEOUT:-0} \
  VNC_RESOLUTION=${ARG_VNC_RESOLUTION:-1024x768} \
  VNC_USER=${ARG_VNC_USER:-headless:headless}

### Be sure to use root user
USER 0

WORKDIR ${HOME}

### Copy pre-configured Firefox profile
COPY [ "./src/profile/", "./.mozilla/" ]

### Change owner
RUN chown -R $VNC_USER ./.mozilla

### Switch to the non-root user
USER ${VNC_USER}

### Issue #7 (base): Mitigating problems with foreground mode
WORKDIR ${STARTUPDIR}
