# docker build -f Dockerfile-plus-preferences -t accetto/ubuntu-vnc-xfce-firefox-plus-preferences .
# docker build -f Dockerfile-plus-preferences -t accetto/ubuntu-vnc-xfce-firefox-plus-preferences:dev .
# docker build -f Dockerfile-plus-preferences --build-arg BASETAG=dev -t accetto/ubuntu-vnc-xfce-firefox-plus-preferences:dev .
# docker build -f Dockerfile-plus-preferences --build-arg ARG_VNC_USER=root:root -t accetto/ubuntu-vnc-xfce-firefox-plus-preferences:root .
# docker build -f Dockerfile-plus-preferences --build-arg BASETAG=rolling -t accetto/ubuntu-vnc-xfce-firefox-plus-preferences:rolling .

ARG BASETAG=latest

FROM accetto/ubuntu-vnc-xfce-firefox-plus:${BASETAG}

LABEL \
    any.accetto.description="Headless Ubuntu VNC/noVNC container with Xfce desktop and Firefox with preferences" \
    any.accetto.display-name="Headless Ubuntu/Xfce VNC/noVNC container with Firefox preferences"

### Arguments can be provided during build
ARG ARG_VNC_BLACKLIST_THRESHOLD
ARG ARG_VNC_BLACKLIST_TIMEOUT
ARG ARG_VNC_RESOLUTION
ARG ARG_VNC_USER

ENV \
  VNC_BLACKLIST_THRESHOLD=${ARG_VNC_BLACKLIST_THRESHOLD:-20} \
  VNC_BLACKLIST_TIMEOUT=${ARG_VNC_BLACKLIST_TIMEOUT:-0} \
  VNC_RESOLUTION=${ARG_VNC_RESOLUTION:-1024x768} \
  VNC_USER=${ARG_VNC_USER:-headless:headless}

### Be sure to use root user
USER 0

WORKDIR ${HOME}

### Put all the user preferences you want to force administratively into the file 'all-accetto.js'.
### The preferences will be forced for each session in all profiles.
### The VNC user ('headles:headless' by default) will get permissions to modify the file.
### The file is currently empty. The fix for issue #2 has been moved to 'user.js'.
COPY [ "./src/firefox/all-accetto.js", "/usr/lib/firefox/browser/defaults/preferences/" ]

### Copy the file with default user preferences.
### The preferences will be forced for each session, but only in the profile containing the file.
### Make also a backup copy of the file (/headless/.mozilla/firefox/user.js.txt).
### The VNC user ('headles:headless' by default) will get permissions to modify or delete the file.
COPY [ "./src/firefox/user.js", "./.mozilla/firefox/profile0.default/" ]
COPY [ "./src/firefox/user.js", "./firefox.backup/profile0.default/user.js" ]

### Fix permissions
RUN \
    chgrp $(id -g $(echo "$VNC_USER" | cut -d : -f 1)) /usr/lib/firefox/browser/defaults/preferences/all-accetto.js \
    && chmod 664 /usr/lib/firefox/browser/defaults/preferences/all-accetto.js \
    && chown $VNC_USER ./.mozilla/firefox/profile0.default/user.js \
    && chmod 600 ./.mozilla/firefox/profile0.default/user.js \
    && chown $VNC_USER ./firefox.backup/profile0.default/user.js \
    && chmod 600 ./firefox.backup/profile0.default/user.js

ENV REFRESHED_AT 2019-04-28

### Switch to back non-root user
USER ${VNC_USER}

### Issue #7 (base): Mitigating problems with foreground mode
WORKDIR ${STARTUPDIR}
